### ISSUE TITLE
Mutant type statistics in file report

### ISSUE THREAD

**Issue by k3rn31** [go-gremlins/gremlins#134]
Add some statistics when outputting to file:

```json
{
  "CONDITIONALS_NEGATION": 10,
  "CONDITIONALS_BOUNDARY": 8,
  "INCREMENT_DECREMENT": 3
}
```

**Comment by rzeAkbari** [comment]
The problem comes form a division by zero issue. In case we have only not covered mutations report, efficacy becomes NAN, hence facing marshalling issues later on.
```
rep.tEfficacy = float64(rep.killed) / float64(rep.killed+rep.lived) * 100
```
tests efficacy should be calculated only if the number of killed is grater than zero, otherwise it keeps its zero value, so we avoid division by zero. 
does this make sense to you @k3rn31 ?
