### ISSUE TITLE
TestMutantDefaultStatus doesn't check whether there are unexpected mutants in mutationEnabled map

### ISSUE THREAD

**Issue by vsvastey** [go-gremlins/gremlins#142]
Testing improvement.

If we create a new mutant and place it in mutationEnabled map, saying for example that it is enabled by default, the test TestMutantDefaultStatus won't catch this. So we will have an unexpected mutator enabled by default.

The test (or a new one) should check whether there is no mutators in the map other than the ones listed in the test.

**Comment by k3rn31** [comment]
Hello,
it is expected that when you create a new mutant, you add a test case for it. Rather than a new test, I would check if all the mutants in the test cases are in `mutant.MutantTypes` and vice versa.

At the moment, adding a new MutantType involves touching several parts of gremlins and tests. Maybe we can think of ways to make it more straightforward to add a mutant. At least for simple token based mutants which just involve adding a new entry in the MutantTypes and TokenMutantType mappings.

For example, it is expected that a new test case is added to TestMutations and TestTypeString. Maybe at least some of these can be "automatised".
