### ISSUE TITLE
Unreliable results on multi core machine

### ISSUE THREAD

**Issue by hknutzen** [go-gremlins/gremlins#170]
### Bug Description

The output of gremlins changes from run to run on a multi core server.

I found this when analyzing my project. Different runs with identical input and identical parameters gives diferent output.

Then it tried it on the source code of gremlins itself and could reproduce the behaviour. 

### To Reproduce

```
git clone https://github.com/go-gremlins/gremlins.git
# currently commit a3cee2
cd gremlins
cd cmd/gremlins
go install
cd ../../internal/gomodule/
# run gremlins multiple times on a 12 core machine
# the output differs

### 1. run
gremlins --config /dev/null run
Starting...
Gathering coverage... done in 296.457292ms
  NOT VIABLE ARITHMETIC_BASE at gomodule.go:59:28
      KILLED CONDITIONALS_NEGATION at gomodule.go:41:10
      KILLED CONDITIONALS_NEGATION at gomodule.go:45:9
      KILLED CONDITIONALS_NEGATION at gomodule.go:68:9
      KILLED CONDITIONALS_NEGATION at gomodule.go:80:61
      KILLED CONDITIONALS_NEGATION at gomodule.go:63:9
      KILLED CONDITIONALS_NEGATION at gomodule.go:84:8

Mutation testing completed in 629 milliseconds 668 microseconds
Killed: 6, Lived: 0, Not covered: 0
Timed out: 0, Not viable: 1
Test efficacy: 100.00%
Mutator coverage: 100.00%

### 2. run
gremlins --config /dev/null run
Starting...
Gathering coverage... done in 313.665794ms
      KILLED CONDITIONALS_NEGATION at gomodule.go:80:61
      KILLED CONDITIONALS_NEGATION at gomodule.go:63:9
      KILLED CONDITIONALS_NEGATION at gomodule.go:68:9
      KILLED CONDITIONALS_NEGATION at gomodule.go:41:10
      KILLED CONDITIONALS_NEGATION at gomodule.go:45:9
      KILLED ARITHMETIC_BASE at gomodule.go:59:28
      KILLED CONDITIONALS_NEGATION at gomodule.go:84:8

Mutation testing completed in 622 milliseconds 808 microseconds
Killed: 7, Lived: 0, Not covered: 0
Timed out: 0, Not viable: 0
Test efficacy: 100.00%
Mutator coverage: 100.00%

### 3. run
gremlins --config /dev/null run
Starting...
Gathering coverage... done in 312.980288ms
  NOT VIABLE ARITHMETIC_BASE at gomodule.go:59:28
      KILLED CONDITIONALS_NEGATION at gomodule.go:45:9
      KILLED CONDITIONALS_NEGATION at gomodule.go:41:10
       LIVED CONDITIONALS_NEGATION at gomodule.go:63:9
      KILLED CONDITIONALS_NEGATION at gomodule.go:68:9
      KILLED CONDITIONALS_NEGATION at gomodule.go:84:8
      KILLED CONDITIONALS_NEGATION at gomodule.go:80:61

Mutation testing completed in 598 milliseconds 274 microseconds
Killed: 5, Lived: 1, Not covered: 0
Timed out: 0, Not viable: 1
Test efficacy: 83.33%
Mutator coverage: 100.00%
```

### Found behaviour

The output differs.

### Expected behaviour

The output is identical.

We get identical output, when run with only one worker as
`gremlins --config /dev/null run --workers 1`

### Operating System

- OS: Debian
- Version 11.5
- CPU: Intel Xeon, 12 cores

**Comment by k3rn31** [comment]
Thanks for the bug report. I noticed this behaviour a few day ago (didn't open the bug yet) and started investigating. The cause is unclear, and all the help to find a solution is welcome.

**Comment by alessio-perugini** [comment]
@k3rn31 Ok I run some bunch of tests and the problem was that we we're not passing the dir in the exec command. Doing the `os.Chdir` does not guarantee us that the command will be run in the path that the current `mutantExecutor` is dealing with.
```go
defer func(d string) {
_ = os.Chdir(d)
}(currDir)
_ = os.Chdir(rootDir)
```

So the snippet I proposed in the previous commend indeed works. I was getting mixed feelings because when I tried on a small pkg like the `gomodule` it did work but when I switched to a bigger one like `coverage` I run in a lot of timeouts and thought the fix wasn't enough. I guess the reason is that we pay the scheduling time of the goroutines.

**Comment by k3rn31** [comment]
Hi @alessio-perugini, great catch! 
Let’s test this thoroughly and provide the fix. Definitely makes sense!
Our intuition was that something with the workdir was messed up 😅

The increased timeout problem is due to the excessive number of tests running concurrently but not in parallel. That’s why in integration mode we run on half workers. Maybe we can come up with a better algorithm to determine the number of worker’s to use.
Hopefully, the new timeouts implementation will help in this regard.

**Comment by k3rn31** [comment]
I did a quick test and it seems stable.

I was thinking that since we already have the workday on the Mutator, maybe we can add a method to the Mutator interface to get the workdir instead of passing it to the run method. 

And do this in `runTests()`

```go
cmd := m.execContext(ctx, "go", m.getTestArgs(pkg, timeout)...)
cmd.Dir = m.mutant.Workdir()
```

What do you think?

**Comment by alessio-perugini** [comment]
@k3rn31 agree :smile:  I'm opening the PR asap
